[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.mbstring", "php82Extensions.tokenizer", "php82Extensions.xml", "php82Extensions.ctype", "php82Extensions.fileinfo", "php82Extensions.openssl", "php82Extensions.curl", "php82Extensions.intl", "composer", "pecl"]

[phases.install]
cmds = [
  "pecl install mongodb",
  "echo 'extension=mongodb.so' >> $(php --ini | grep 'Loaded Configuration' | awk '{print $NF}')"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-scripts --no-interaction",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
